### PR TITLE
Updated Makefile

### PR DESCRIPTION
**Pull request by gautamkrishnar**
I think just changing it to just g++ will make it work for now.
Is it necessary to use the g++ version 4.2?

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
The build is running successfully on my g++ version.
```
$g++ -dumpversion
5.3.1
```
Why CI is failing?

**Comment by ParadoxZero** [comment]
The CI fails as the project needs g++ 4.8 or above to compile according to c++11 standard.
Travis uses ubuntu12 which has g++4.6. So its needs g++4.8 explicitly.

**Comment by gautamkrishnar** [comment]
I will work on this after my exams. 👍

**Comment by ParadoxZero** [comment]
Don't worry, its a small change, will do that tomorrow.

**Comment by ParadoxZero** [comment]
Done 👍

**Comment by gautamkrishnar** [comment]
Still have a lots of works to do!.... @ParadoxZero 😄

**Comment by ParadoxZero** [comment]
In the makefile?

**Comment by gautamkrishnar** [comment]
Yes. We need to check the g++ version and make the buid fail if the version is less than the required version.

**Comment by ParadoxZero** [comment]
That would happen on its own right?

**Comment by gautamkrishnar** [comment]
I am not sure about that.

**Comment by ParadoxZero** [comment]
There we go, I think this completes the work.

**Comment by ParadoxZero** [comment]
Done 👍  @gautamkrishnar 
The makefile will give error in case the version is below 4.8

**Comment by gautamkrishnar** [comment]
Kudos @ParadoxZero ❤️

**Pull request merged**
